site_name: GRM-LABS
site_url: https://grm-labs.github.io/
dev_addr: "127.0.0.1:8001"
copyright: >
  Copyright &copy; 2024 Germán Ruiz
theme:
  name: material
  language: es
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.expand
    - content.code.annotate
    - search.share
    - search.suggest
    - content.tabs.link
    - announce.dismiss
  palette:
    scheme: youtube
  font:
    text: Fira Sans
    code: Ubuntu Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/grm-labs
      name: Github / GRM - Labs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gruizmudarra/
      name: Linked In / Germán Ruiz
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/grm.labs
      name: Instagram / GRM - Labs

extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - material/search
  - tags
  - social

nav:
  - Home: index.md
  - Projects: blog/index.md
  - About me: about.md
